# Generated by Django 5.2.6 on 2025-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('usuário', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
