# Generated by Django 5.2.6 on 2025-09-13 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
