# Generated by Django 5.2.6 on 2025-09-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_receitas', '0002_cadastro_criado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='usuário',
            new_name='usuario',
        ),
    ]
