# Generated by Django 5.2.6 on 2025-09-13 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receitas', '0003_rename_usuário_cadastro_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('ingredientes', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_receitas.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='cadastro',
        ),
        migrations.AddField(
            model_name='receitas',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_receitas.usuario'),
        ),
    ]
