# Generated by Django 5.2.6 on 2025-09-14 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_receitas', '0004_categorias_receitas_usuario_delete_cadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='receitas',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
