# Generated by Django 5.2.6 on 2025-09-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_receitas', '0006_categoria_receitas_categoria'),
        ('app_receitas', '0007_popular_categorias'),
    ]

    operations = [
    ]
